language: ruby
rvm:
  - 2.6.2
cache:
  - bundler
before_script:
  - bundle exec rake db:create
  - bundle exec rake db:migrate
deploy:
  provider: heroku
  api_key: HEROKU_API_KEY
  app:
    staging: trainer-app-api-staging
    master: trainer-app-api-prod
    run:
      - "rake db:migrate"
      - "rake cleanup"
