language: ruby
rvm:
  - 2.6.2
cache:
  - bundler
before_script:
  - bundle exec rake db:create
  - bundle exec rake db:migrate
deploy:
  provider: heroku
  api_key:
    api_key: HEROKU_API_KEY
 app:
    staging: trainer-app-api-staging
    master: trainer-app-api-prod
  on:
    repo: mradeybee/time-tracker-api
  run:
    - "rake db:migrate"
    - "rake cleanup"
