default: &default
  adapter: postgresql
  encoding: unicode
  host: 127.0.0.1
  pool: 5

development:
  <<: *default
  database: training_app_api_development
  username: postgres
  password: password

test:
  <<: *default
  database: training_app_api_test
  username: postgres
  password: password

production:
  url: <%= ENV['DATABASE_URL'] %>
